### Create Banking User
POST http://localhost:8080/api/v1/banking-users/create
Content-Type: application/json

{
  "debitCardNumber": "55511133312",
  "name": "Charles Leclerc",
  "id": 27,
  "balance": 180000,
  "active": true
}


### DEPOSIT
PUT http://localhost:8080/api/v1/banking-users/deposit?accountNumber=555111333&amount=500


### UPDATE USER
PUT http://localhost:8080/api/v1/banking-users/update/55511133312
Content-Type: application/json

{
  "debitCardNumber": "20398109381",
  "name": "Lewis Hamilton",
  "id": 44,
  "balance": 185000,
  "active": true
}

###CREATE LECLERC
POST http://localhost:8080/api/v1/banking-users/create
Content-Type: application/json

{
"debitCardNumber": "11111111111",
"name": "Max Verstappen",
"id": 27,
"balance": 180000,
  "active": true
}

### TRANSFER
POST http://localhost:8080/api/v1/banking-users/transfer?fromAccount=11111111111&toAccount=20398109381&amount=10234

### CREATE ACCOUNT
POST http://localhost:8080/api/v1/banking-users/create
Content-Type: application/json

{
  "debitCardNumber": "123298218973279131",
  "name": "Lando Cortis",
  "id": 1,
  "balance": 21,
  "active": true
}

### CREATE ACCOUNT
POST http://localhost:8080/api/v1/banking-users/create
Content-Type: application/json

{
  "debitCardNumber": "000000000000",
  "name": "FIA",
  "id": 1,
  "balance": 1290321033123,
  "active": true
}


### TRANSFER
POST http://localhost:8080/api/v1/banking-users/transfer?fromAccount=000000000000&toAccount=123298218973279131&amount=20000000

### DELETE ACCOUNT
DELETE http://localhost:8080/api/v1/banking-users/delete?accountNumber=000000000000
