### Create Banking User
POST http://localhost:8080/api/v1/banking-users/create
Content-Type: application/json

{
  "debitCardNumber": "555111333",
  "name": "Charles Leclerc",
  "id": 27,
  "balance": 180000
}


### DEPOSIT
PUT http://localhost:8080/api/v1/banking-users/deposit?accountNumber=555111333&amount=500


### UPDATE USER
PUT http://localhost:8080/api/v1/banking-users/update/555111333
Content-Type: application/json

{
  "debitCardNumber": "20398109381",
  "name": "Lewis Hamilton",
  "id": 44,
  "balance": 185000
}

###CREATE LECLERC
POST http://localhost:8080/api/v1/banking-users/create
Content-Type: application/json

{
"debitCardNumber": "555111333",
"name": "Charles Leclerc",
"id": 27,
"balance": 180000
}

### TRANSFER
POST http://localhost:8080/api/v1/banking-users/transfer?fromAccount=555111333&toAccount=20398109381&amount=10234
